### ISSUE TITLE
Method CreateFragment has no valid ret instruction

### ISSUE THREAD

**Issue by jjkakakk** [andreycha/tangerine#14]
I get a stacktrace a la:

System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Method 'CreateFragment' has no valid ret instruction
  Source=Tangerine
  StackTrace:
       at Tangerine.BLL.AssemblyPatcher.LogReturnValue(MethodDefinition methodDefinition) in c:\Users\blah\Desktop\tan\Tangerine\BLL\XAP\AssemblyPatcher.cs:line 512
       at Tangerine.BLL.AssemblyPatcher.PatchMethod(MethodDefinition methodDefinition, TypeDefinition typeDefinition, MethodHook methodHook) in c:\Users\blah\Desktop\tan\Tangerine\BLL\XAP\AssemblyPatcher.cs:line 160
       at Tangerine.BLL.AssemblyPatcher.PatchAssembly() in c:\Users\blah\Desktop\tan\Tangerine\BLL\XAP\AssemblyPatcher.cs:line 116
       at Tangerine.BLL.Tasks.PatchTask.Run() in c:\Users\blah\Desktop\tan\Tangerine\BLL\Tasks\PatchTask.cs:line 67
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException:

**Comment by andreycha** [comment]
Hi.
Thanks for the feedback. Сould you please send me CIL code of CreateFragment method or, say, 10 last instructions?
